### ISSUE TITLE
Hacking the default post type is not advisable

### ISSUE THREAD

**Issue by mandiwise** [redacademy/bix-summer-2016#1]
Please add a custom post type for stories and move your story content over to that post type, instead of hacking the default "post" post type.

It will of course be redundant to have "posts" and "stories" in the back-end UI, but you can hide default posts like so:

https://gist.github.com/mandiwise/2ea571ae0773b340af5a

**Comment by wongerchris** [comment]
Stories Custom Post Type has been added and default posts has been hidden from back-end
