### ISSUE TITLE
Don't use "get_" functions where they're not needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/bix-summer-2016#3]
For example on line 43 of single.php, you have:

``` php
echo esc_url( get_permalink(67) );
```

You have to echo it because "get_" simple returns the value, while this template tag does that but also echoes it:

``` php
esc_url( the_permalink(67) );
```

Also, is this the best way to fetch that link? What happens if someone deletes that page and the ID is not longer applicable?

**Comment by Imarky05** [comment]
The markup for single.php has been changed.

**Comment by Imarky05** [comment]
The markup has been updated.
